### ISSUE TITLE
Snippet based search on the web UI.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#335] opened 2015-08-05 04:52 UTC
This feature will allow a user to paste the code snippet and hit parse/process. We will highlight the keyword from it, he can select and hit search. 

This is essentially the unique feature of kodebeagle.

**Comment by hashd** [comment] 2015-08-05 07:04
Duplicate of #240

**Closed by hashd** 2015-08-05 07:04 UTC
Labels: web-ui
